server:
  port: 80
spring:
  application:
    name: consumersProject

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: localhost # 指定自己的ip信息，不指定的话会自己寻找
  client:
    register-with-eureka: false
    service-url: #EurekaServer集群所有地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

